### ISSUE TITLE
Icebreaker Analytics

### ISSUE THREAD

**Issue by gavinbeere1** [OfficeDev/microsoft-teams-apps-icebreaker#133]
Hi guys,

We have been happily using icebreaker for 2 weeks and it is great!

We are wondering if there is a way to see some analytics on the icebreaker, for example, to show who has paused all matches, who has successfully completed their match.

Is there any way you could advise on this please? Thanks.

**Comment by Nandeesh82** [comment]
Hi Gavin, Please let me know if you are able to get analytics on the icebreaker, we need to get number of pairs completed. Thanks
@gavinbeere1

**Comment by Nandeesh82** [comment]
@jotrick , We have deployed Icebreaker now, but we need to get analytics at the end of week or Month, Like how many Pair completed and how many meetings done, how many users opted out? Could you please help how to get these analytics or statistics' for icebreaker bot.

**Comment by chartaam** [comment]
There is some documentation about Telemetry here: https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/wiki/Telemetry
But I don't know enough about Analytics to really figure out how to get a good report.

**Comment by aosolis** [comment]
Hi @Nandeesh82:
- Users opted out: The [Users collection](https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/wiki/Data-stores) contains the opt-out status of all users
- Completed pairs: You can query the `customEvents` table in Application Insights for the [ProcessedPairups](https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/wiki/Telemetry) event, and get the number of pairs/users notified during the timeframe of your query.

The current version of Icebreaker doesn't track the pairups, so it can't tell you who was matched with whom and when.
However, the source is freely available to extend with your specific use cases.

**Comment by gavinbeere1** [comment]
Hi Adrian, Nandeesh,

We have progressed with the icebreaker analytics, but we are still unable
to query the desired results.

Not sure if we are on the right track, but we are unable to query the log
to show users opted out, successful pairs etc.

We have followed the link you provided below, but still can't seem to
progress:
Data stores · OfficeDev/microsoft-teams-apps-icebreaker Wiki · GitHub
<https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/wiki/Data-stores#users-collection>

I have also attached the log screenshot below where we are querying this.

Can you assist with helping us obtain this information for the Icebreaker
app please? Thanks.

[image: image.png]

**Comment by Nandeesh82** [comment]
Hi gavin, @gavinbeere1 

Applications insights will provide details about pairs notified count, user notified count etc, please check user collection details in application insights and filter the data required.
https://docs.microsoft.com/en-us/azure/azure-monitor/app/usage-segmentation
